language: android
dist: trusty
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    # The BuildTools version used by your project
    - extra

    # The SDK version used to compile your project

    # Additional components
    - extra-google-google_play_services
    # Specify at least one system image,
    - sys-img-x86-android-29
    - sys-img-armeabi-v7a-android-17
    licenses:
    - '.+'
    sudo: required

    jdk:
    - oraclejdk8

    install: true

    script:
    - sudo apt-get update && sudo apt-get install oracle-java8-installer
    - java -version

    script:
    - ./gradlew assembleDebug
